apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: docker.io/nitheesh86/microservice-frontend-dev
    argocd-image-updater.argoproj.io/update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/myalias.force-update: "true"
spec:
  project: craftista
  source:
    repoURL: https://github.com/nitheeshp-irl/microservice-helmcharts
    targetRevision: main
    path: service-charts/frontend
    helm:
      parameters:
        - name: image.repository
          value: docker.io/nitheesh86/microservice-frontend
        - name: image.tag
          value: "1.0.0"
        
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true