apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-dev
  namespace: argocd
spec:
  project: craftista
  source:
    repoURL: https://github.com/nitheeshp-irl/microservice-helmcharts
    targetRevision: main
    path: service-charts/voting
    helm:
      valueFiles:
        - ../../env/dev/voting/voting-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: voting-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

