apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: catalogue-warehouse
  namespace: craftista
spec:
  freightCreationPolicy: Automatic
  interval: 1440m
  subscriptions:
    - image:
        repoURL: docker.io/nitheesh86/microservice-catalogue
        imageSelectionStrategy: SemVer
        discoveryLimit: 20