catalogue:
  replicaCount: 2
  image:
    repository: nitheesh86/microservice-catalogue
    tag: "latest"
  service:
    type: ClusterIP
    port: 6000
  env:
    DB_HOST: catalogue-db
    DB_PORT: 5432
    DB_USER: catalogue
    DB_PASS: catalogue123
    DB_NAME: catalogue-db
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

catalogue-db:
  replicaCount: 1
  image:
    repository: postgres
    tag: "16.2-alpine3.19"
  service:
    type: ClusterIP
    port: 5432
  postgres:
    user: catalogue
    password: catalogue123
    db: catalogue-db
  env:
    POSTGRES_USER: catalogue
    POSTGRES_PASSWORD: catalogue123
    POSTGRES_DB: catalogue-db
  persistence:
    enabled: false  # Set true if using PVCs

frontend:
  replicaCount: 2
  image:
    repository: nitheesh86/microservice-frontend
    tag: "latest"
  service:
    type: NodePort
    port: 30080
  env:
    VITE_API_BASE_URL: http://catalogue:6000
  resources: {}

recommendation:
  replicaCount: 2
  image:
    repository: nitheesh86/microservice-recommendation
    tag: "latest"
  service:
    type: ClusterIP
    port: 8080
  env:
    DB_HOST: catalogue-db
    DB_PORT: 5432
    DB_USER: catalogue
    DB_PASS: catalogue123
    DB_NAME: catalogue-db
  resources: {}

voting:
  replicaCount: 1
  image:
    repository: nitheesh86/microservice-voting
    tag: "latest"
  service:
    type: ClusterIP
    port: 8081
  env:
    API_BASE_URL: http://catalogue:6000
  resources: {}
