apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice-frontend.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: 3000
  selector:
    app: {{ include "microservice-frontend.fullname" . }}