apiVersion: kargo.akuity.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: frontend-verification
  namespace: kargo-system
spec:
  metrics:
    - name: deployment-health
      provider:
        job:
          spec:
            backoffLimit: 1
            template:
              spec:
                containers:
                - name: check-deployment
                  image: bitnami/kubectl:latest
                  command:
                  - /bin/bash
                  - -c
                  - |
                    # Check if frontend deployment is healthy
                    SERVICE="frontend"
                    NAMESPACE="demo"
                    
                    echo "Checking deployment status for $SERVICE in $NAMESPACE namespace"
                    
                    # Check if deployment exists
                    kubectl get deployment $SERVICE -n $NAMESPACE &> /dev/null
                    if [ $? -ne 0 ]; then
                      echo "Deployment $SERVICE not found in namespace $NAMESPACE"
                      exit 1
                    fi
                    
                    # Check if deployment is available
                    AVAILABLE=$(kubectl get deployment $SERVICE -n $NAMESPACE -o jsonpath='{.status.availableReplicas}')
                    DESIRED=$(kubectl get deployment $SERVICE -n $NAMESPACE -o jsonpath='{.status.replicas}')
                    
                    if [ -z "$AVAILABLE" ] || [ "$AVAILABLE" -lt "$DESIRED" ]; then
                      echo "Deployment $SERVICE is not fully available. Available: $AVAILABLE, Desired: $DESIRED"
                      exit 1
                    fi
                    
                    # Check if deployment is up-to-date
                    UPDATED=$(kubectl get deployment $SERVICE -n $NAMESPACE -o jsonpath='{.status.updatedReplicas}')
                    if [ "$UPDATED" -lt "$DESIRED" ]; then
                      echo "Deployment $SERVICE is not fully updated. Updated: $UPDATED, Desired: $DESIRED"
                      exit 1
                    fi
                    
                    echo "Frontend deployment is healthy"
                    exit 0
                restartPolicy: Never