apiVersion: kargo.akuity.io/v1alpha1
kind: Freight
metadata:
  name: frontend-freight
  namespace: craftista
  labels:
    kargo.akuity.io/alias: latest
origin:
  kind: Warehouse
  name: frontend-warehouse