apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
spec:
  project: default
  destination:
    namespace: kargo
    server: https://kubernetes.default.svc
  source:
    repoURL: ghcr.io/akuity/kargo-charts
    chart: kargo
    targetRevision: 1.2.0
    helm:
      parameters:
        - name: api.adminAccount.passwordHash
          value: 6YInjWhtiHIq10042CeNPOXBvtVT9jnJ
        - name: api.adminAccount.tokenSigningKey
          value: M6BgMWph4ejetJLRtCEVwL1qS9pgqQ88
  syncPolicy:
    automated: {}
