apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: frontend-auto-promote
  namespace: kargo-system
spec:
  sourceStages:
    - name: dev
  targetStage:
    name: stage
  autoPromotionEnabled: true
