apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote-to-staging
  namespace: craftista
spec:
  steps:
    - uses: git-clone
      config:
        repoURL: https://nitheeshp-irl:xxxxxxxxx@github.com/nitheeshp-irl/microservice-helmcharts.git
        checkout:
          - branch: main
            path: ./repo
    - uses: git-commit
      config:
        path: ./repo
        message: "Promote frontend from dev to stage"
    - uses: git-push
      config:
        path: ./repo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote-to-prod
  namespace: craftista
spec:
  steps:
    - uses: git-clone
      config:
        repoURL: https://nitheeshp-irl:xxxxxxxxx@github.com/nitheeshp-irl/microservice-helmcharts.git
        checkout:
          - branch: main
            path: ./repo
    - uses: git-commit
      config:
        path: ./repo
        message: "Promote frontend from stage to prod"
    - uses: git-push
      config:
        path: ./repo