apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote-to-staging
  namespace: craftista
spec:
  vars:
  - name: image
    value: docker.io/nitheesh86/microservice-frontend
  - name: repoURL
    value: https://github.com/nitheeshp-irl/microservice-helmcharts
  - name: branch
    value: main
  - name: envPath
  - name: argocdApp
  steps:
    - uses: git-clone
      config:
        repoURL: ${{ vars.repoURL }}
        checkout:
        - commit: ${{ commitFrom( vars.repoURL ).ID }}
          path: ./src
        - branch: ${{ vars.branch }}
          path: ./out
    - uses: yaml-update
      as: update-image
      config:
        path: ./out/${{ vars.envPath }}/frontend/frontend-values.yaml
        updates:
        - path: image
          value: ${{ imageFrom( vars.image ).Tag }}
    - uses: git-commit
      as: commit
      config:
        path: ./out
        message: ${{ task.outputs['update-image'].commitMessage }}
    - uses: git-push
      config:
        path: ./out
    - uses: argocd-update
      config:
        apps:
        - name: ${{ vars.argocdApp }}