apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: frontend-auto-promote
  namespace: frontend
spec:
  sourceStages:
    - name: dev
      namespace: frontend
  targetStage:
    name: stage
    namespace: frontend
  autoPromotionEnabled: true