apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: frontend
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stage
  namespace: frontend
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: frontend
spec:
  requestedFreight:
    - origin:
        kind: Warehouse