apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: frontend-dev-stage
  namespace: craftista
  annotations:
    kargo.akuity.io/color: blue
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: frontend-warehouse
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote-to-staging
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: frontend-staging-stage
  namespace: craftista
  annotations:
    kargo.akuity.io/color: orange
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: frontend-warehouse
      sources:
        stages:
          - frontend-dev-stage
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote-to-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: frontend-prod-stage
  namespace: craftista
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: frontend-warehouse
      sources:
        stages:
          - frontend-staging-stage
