apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: frontend-warehouse
  namespace: kargo-system
spec:
  interval: 5m
  subscriptions:
    - image:
        repoURL: docker.io/nitheesh86/microservice-frontend
        imageSelectionStrategy: SemVer
