apiVersion: v2
name: craftista
description: Umbrella chart for Craftista microservices
version: 0.1.0
type: application

dependencies:
  - name: catalogue
    version: 0.1.0
    repository: "file://charts/catalogue"
  - name: catalogue-db
    version: 0.1.0
    repository: "file://charts/catalogue-db"
  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"
  - name: recommendation
    version: 0.1.0
    repository: "file://charts/recommendation"
  - name: voting
    version: 0.1.0
    repository: "file://charts/voting"
