apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalogue-db-staging
  namespace: argocd
spec:
  project: craftista
  source:
    repoURL: https://github.com/nitheeshp-irl/microservice-helmcharts
    targetRevision: main
    path: service-charts/catalogue-db
    helm:
      valueFiles:
        - ../../env/staging/catalogue-db.yaml
        
  destination:
    server: https://kubernetes.default.svc
    namespace: catalogue-db-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true