apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - catalogue.yaml
  - catalogue-db.yaml
  - frontend.yaml
  - recommendation.yaml
  - voting.yaml

commonLabels:
  environment: staging
  app.kubernetes.io/managed-by: kustomize

namespace: argocd