apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recommendation-staging
  namespace: argocd
spec:
  project: craftista
  source:
    repoURL: https://github.com/nitheeshp-irl/microservice-helmcharts
    targetRevision: main
    path: service-charts/recommendation
    helm:
      valueFiles:
        - ../../env/staging/recommendation.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: recommendation-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true