apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-staging
  namespace: argocd
spec:
  project: craftista
  source:
    repoURL: https://github.com/nitheeshp-irl/microservice-helmcharts
    targetRevision: main
    path: service-charts/voting
    helm:
      valueFiles:
        - ../../env/staging/voting.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: voting-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true