apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalogue-prod
  namespace: argocd
spec:
  project: craftista
  source:
    repoURL: https://github.com/nitheeshp-irl/microservice-helmcharts
    targetRevision: main
    path: service-charts/catalogue
    helm:
      valueFiles:
        - ../../env/prod/catalogue/catalogue.yaml
        - ../../env/prod/catalogue/catalogue-image.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true