apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalogue-db-prod
  namespace: argocd
spec:
  project: craftista
  source:
    repoURL: https://github.com/nitheeshp-irl/microservice-helmcharts
    targetRevision: main
    path: service-charts/catalogue-db
    helm:
      valueFiles:
        - /env/prod/catalogue-db/catalogue-db-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true