apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - catalogue/catalogue-values.yaml
  - catalogue-db/catalogue-db-values.yaml
  - frontend/frontend-values.yaml
  - recommendation/recommendation-values.yaml
  - voting/voting-values.yaml

commonLabels:
  environment: dev
  managed-by: kustomize