apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice-frontend.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8081
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "microservice-frontend.fullname" . }}